### PR TITLE
Fix for 3.8

### PR DESCRIPTION
**Pull request by rukano**
Hi, I will work a little bit on this layer to get it running more easy and reliable. I justs did a readme and updated the paths for the current 3.8 version, if you care to merge, we can work together on this. :)

### CODE REVIEW

**Comment by dathinaios** [comment]
Thanks,

I was trying to get this working but I just switched from vim so I am not sure how. Any help is greatly appreciated :)

Also see here: https://github.com/syl20bnr/spacemacs/issues/7229

**Comment by rukano** [comment]
Cool thanks! I'm too deep in the emacs world to switch, and have all my sc yasnippets there... so I'd rather work a little on this :D At least to get it running smoothly for a first installer... Thanks for the merge!

**Comment by dathinaios** [comment]
I made a few changes so make sure you pull before you start working on this. 

1. I changed the structure so that it follows the convention for `spacemacs` layers in case we want to submit it to the `spacemacs` project at a later time.
2. I 've changed the default path for the `SuperCollider.app` to `Applications` as this is the convention on the `Mac`.

Thanks!

**Comment by dathinaios** [comment]
I got it working!

\o/

**Comment by rukano** [comment]
Awesome! thanks for the effort! Will see if I can add some other stuff! Thanks!

**Comment by rukano** [comment]
The solution works! But it's a little bit destructive, since the normal SuperCollider.app won't compile (Duplicated Document.sc) class. I know there is this `'(sclang-library-configuration-file "path_to/emacs_cfg.yaml")` which I set in the `custon-set-variables` (in my old emacs system, not spacemacs)... But this doesn't seem to be working. In the config file is something like:
```yaml
includePaths:
    - /Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary
    - /Library/Application Support/SuperCollider/Extensions
    - /Users/username/.emacs.d/private/supercollider/sc
excludePaths:
    []
postInlineWarnings: false
```
So the sclang started from emacs will compile extra the emacs path, and the normal SuperCollider.app won't notice anything... Do you have any idea why setting the path to library configuration file is not working? I've tried doing it in several places... in .spacemacs, in .packages.el... no success... Only succeeded with your version, linking the .sc files directly to the extensions...

**Comment by rukano** [comment]
moving my last comment as a issue for better finding and conversation and visibility for others...

**Pull request merged**
